from config.db import db
from datetime import datetime
import hashlib
import os

# Association table for Licence <-> User (Many-to-Many)
licence_users = db.Table('licence_users',
    db.Column('licence_id', db.Integer, db.ForeignKey('licence.id'), primary_key=True),
    db.Column('user_id', db.Integer, db.ForeignKey('users.id'), primary_key=True)
)

class Licence(db.Model):
    """
    Licence model — stores the product key and expiry for the subscription.
    Can optionally be tied to specific users via the licence_users table.
    """
    __tablename__ = 'licence'

    id           = db.Column(db.Integer,     primary_key=True, autoincrement=True)
    product_key  = db.Column(db.String(100), nullable=False, unique=True)
    machine_id   = db.Column(db.String(100), default=None)
    is_active    = db.Column(db.Boolean,     default=False)
    activated_at = db.Column(db.DateTime,    default=None)
    valid_from   = db.Column(db.DateTime,    default=datetime.utcnow)
    expires_at   = db.Column(db.DateTime,    default=None)
    created_at   = db.Column(db.DateTime,    default=datetime.utcnow)

    # Relationship to User
    users = db.relationship('User', secondary=licence_users, backref=db.backref('licences', lazy='dynamic'))

    def __init__(self, product_key, machine_id=None, valid_from=None, expires_at=None):
        self.product_key = product_key
        self.machine_id  = machine_id
        if valid_from:
            self.valid_from = valid_from
        if expires_at:
            self.expires_at = expires_at

    # ------------------------------------------------------------------
    # Key validation
    # ------------------------------------------------------------------

    @staticmethod
    def validate_key_format(key):
        """
        Check the key matches the expected format: XXXX-XXXX-XXXX-XXXX
        Each segment is exactly 4 alphanumeric characters.
        Returns True if valid format, False otherwise.
        """
        import re
        pattern = r'^[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}$'
        return bool(re.match(pattern, key.upper()))

    @staticmethod
    def generate_key(machine_id=None, year=None):
        """
        Generate a valid product key using HMAC-SHA256.
        Only the developer can generate keys (SECRET_KEY is never shipped to clients).

        Usage (run this yourself to create keys for clients):
            from models.licence import Licence
            key = Licence.generate_key(machine_id='CLIENT-001', year=2026)
            print(key)  # e.g.  A3K9-WX2M-PQ7R-ZT04
        """
        secret  = os.getenv('LICENCE_SECRET', 'change-this-secret-in-production')
        year    = year or datetime.utcnow().year
        seed    = f"{machine_id or 'GLOBAL'}-{year}-{secret}"
        digest  = hashlib.sha256(seed.encode()).hexdigest().upper()
        # Format as XXXX-XXXX-XXXX-XXXX from the first 16 hex chars
        raw = digest[:16]
        return f"{raw[0:4]}-{raw[4:8]}-{raw[8:12]}-{raw[12:16]}"

    @staticmethod
    def verify_key_signature(key, machine_id=None):
        """
        Verify the key was generated by this developer (signature check).
        Returns True if the key matches the expected HMAC for this machine + year.
        """
        year = datetime.utcnow().year
        expected = Licence.generate_key(machine_id=machine_id, year=year)
        # Also accept keys generated for the previous year (grace period)
        expected_prev = Licence.generate_key(machine_id=machine_id, year=year - 1)
        return key.upper() in (expected, expected_prev)

    # ------------------------------------------------------------------
    # Status helpers
    # ------------------------------------------------------------------

    def is_expired(self):
        """Returns True if the licence has passed its expiry date."""
        if not self.expires_at:
            return False
        return datetime.utcnow() > self.expires_at

    def days_remaining(self):
        """Returns how many days are left. Negative means already expired."""
        if not self.expires_at:
            return -1
        delta = self.expires_at - datetime.utcnow()
        return delta.days

    def to_dict(self):
        return {
            'id':           self.id,
            'product_key':  self.product_key,
            'machine_id':   self.machine_id,
            'is_active':    self.is_active,
            'activated_at': self.activated_at.isoformat() if self.activated_at else None,
            'expires_at':   self.expires_at.isoformat()   if self.expires_at   else None,
            'days_remaining': self.days_remaining(),
            'is_expired':   self.is_expired(),
        }

    def __repr__(self):
        return f"<Licence key={self.product_key} expires={self.expires_at}>"


# ------------------------------------------------------------------
# Standalone helper — call this at the top of app.py
# ------------------------------------------------------------------

def check_licence():
    """
    Check if a valid, non-expired licence exists.
    Call this inside app.app_context() at startup.

    Returns:
        (True, licence_obj)  — licence is valid
        (False, 'expired')   — licence exists but has expired
        (False, 'not_found') — no licence row in DB at all
    """
    licence = Licence.query.filter_by(is_active=True).order_by(Licence.id.desc()).first()
    if not licence:
        return False, 'not_found'
    if licence.is_expired():
        return False, 'expired'
    return True, licence
